-- V2: Constraints and indexes (idempotent for Oracle)

-- Unique constraints
DECLARE n NUMBER; BEGIN
  SELECT COUNT(*) INTO n FROM user_constraints WHERE constraint_name = 'UK_USUARIO_EMAIL';
  IF n = 0 THEN EXECUTE IMMEDIATE 'ALTER TABLE USUARIO ADD CONSTRAINT UK_USUARIO_EMAIL UNIQUE (EMAIL)'; END IF;
END;
/

DECLARE n NUMBER; BEGIN
  SELECT COUNT(*) INTO n FROM user_constraints WHERE constraint_name = 'UK_MOTO_PLACA';
  IF n = 0 THEN EXECUTE IMMEDIATE 'ALTER TABLE MOTO ADD CONSTRAINT UK_MOTO_PLACA UNIQUE (PLACA)'; END IF;
END;
/

DECLARE n NUMBER; BEGIN
  SELECT COUNT(*) INTO n FROM user_constraints WHERE constraint_name = 'UK_MOTO_CHASSI';
  IF n = 0 THEN EXECUTE IMMEDIATE 'ALTER TABLE MOTO ADD CONSTRAINT UK_MOTO_CHASSI UNIQUE (CHASSI)'; END IF;
END;
/

-- Foreign keys
DECLARE n NUMBER; BEGIN
  SELECT COUNT(*) INTO n FROM user_constraints WHERE constraint_name = 'FK_VAGA_PATIO';
  IF n = 0 THEN EXECUTE IMMEDIATE 'ALTER TABLE VAGA ADD CONSTRAINT FK_VAGA_PATIO FOREIGN KEY (PATIO_ID) REFERENCES PATIO (ID)'; END IF;
END;
/

DECLARE n NUMBER; BEGIN
  SELECT COUNT(*) INTO n FROM user_constraints WHERE constraint_name = 'FK_MOTO_VAGA';
  IF n = 0 THEN EXECUTE IMMEDIATE 'ALTER TABLE MOTO ADD CONSTRAINT FK_MOTO_VAGA FOREIGN KEY (VAGA_ID) REFERENCES VAGA (ID)'; END IF;
END;
/

DECLARE n NUMBER; BEGIN
  SELECT COUNT(*) INTO n FROM user_constraints WHERE constraint_name = 'FK_DEFEITO_MOTO';
  IF n = 0 THEN EXECUTE IMMEDIATE 'ALTER TABLE DEFEITO ADD CONSTRAINT FK_DEFEITO_MOTO FOREIGN KEY (MOTO_ID) REFERENCES MOTO (ID)'; END IF;
END;
/

DECLARE n NUMBER; BEGIN
  SELECT COUNT(*) INTO n FROM user_constraints WHERE constraint_name = 'FK_ALOCACAO_MOTO';
  IF n = 0 THEN EXECUTE IMMEDIATE 'ALTER TABLE ALOCACAO_MOTO ADD CONSTRAINT FK_ALOCACAO_MOTO FOREIGN KEY (MOTO_ID) REFERENCES MOTO (ID)'; END IF;
END;
/

DECLARE n NUMBER; BEGIN
  SELECT COUNT(*) INTO n FROM user_constraints WHERE constraint_name = 'FK_ALOCACAO_VAGA';
  IF n = 0 THEN EXECUTE IMMEDIATE 'ALTER TABLE ALOCACAO_MOTO ADD CONSTRAINT FK_ALOCACAO_VAGA FOREIGN KEY (VAGA_ID) REFERENCES VAGA (ID)'; END IF;
END;
/

DECLARE n NUMBER; BEGIN
  SELECT COUNT(*) INTO n FROM user_constraints WHERE constraint_name = 'FK_ALOCACAO_MECANICO';
  IF n = 0 THEN EXECUTE IMMEDIATE 'ALTER TABLE ALOCACAO_MOTO ADD CONSTRAINT FK_ALOCACAO_MECANICO FOREIGN KEY (MECANICO_RESPONSAVEL_ID) REFERENCES USUARIO (ID)'; END IF;
END;
/

-- Indexes
DECLARE n NUMBER; BEGIN
  SELECT COUNT(*) INTO n FROM user_indexes WHERE index_name = 'IDX_VAGA_PATIO';
  IF n = 0 THEN EXECUTE IMMEDIATE 'CREATE INDEX IDX_VAGA_PATIO ON VAGA (PATIO_ID)'; END IF;
END;
/

DECLARE n NUMBER; BEGIN
  SELECT COUNT(*) INTO n FROM user_indexes WHERE index_name = 'IDX_MOTO_VAGA';
  IF n = 0 THEN EXECUTE IMMEDIATE 'CREATE INDEX IDX_MOTO_VAGA ON MOTO (VAGA_ID)'; END IF;
END;
/

DECLARE n NUMBER; BEGIN
  SELECT COUNT(*) INTO n FROM user_indexes WHERE index_name = 'IDX_DEFEITO_MOTO';
  IF n = 0 THEN EXECUTE IMMEDIATE 'CREATE INDEX IDX_DEFEITO_MOTO ON DEFEITO (MOTO_ID)'; END IF;
END;
/

DECLARE n NUMBER; BEGIN
  SELECT COUNT(*) INTO n FROM user_indexes WHERE index_name = 'IDX_ALOCACAO_MOTO';
  IF n = 0 THEN EXECUTE IMMEDIATE 'CREATE INDEX IDX_ALOCACAO_MOTO ON ALOCACAO_MOTO (MOTO_ID)'; END IF;
END;
/

DECLARE n NUMBER; BEGIN
  SELECT COUNT(*) INTO n FROM user_indexes WHERE index_name = 'IDX_ALOCACAO_VAGA';
  IF n = 0 THEN EXECUTE IMMEDIATE 'CREATE INDEX IDX_ALOCACAO_VAGA ON ALOCACAO_MOTO (VAGA_ID)'; END IF;
END;
/

