-- V4: Example schema adjustments (Oracle-safe and idempotent)

DECLARE v_exists NUMBER; v_len NUMBER; BEGIN
  SELECT COUNT(*) INTO v_exists FROM USER_TAB_COLUMNS 
  WHERE TABLE_NAME = 'USUARIO' AND COLUMN_NAME = 'SENHA';
  IF v_exists > 0 THEN
    SELECT DATA_LENGTH INTO v_len FROM USER_TAB_COLUMNS 
    WHERE TABLE_NAME = 'USUARIO' AND COLUMN_NAME = 'SENHA';
    IF v_len < 100 THEN
      EXECUTE IMMEDIATE 'ALTER TABLE USUARIO MODIFY (SENHA VARCHAR2(100))';
    END IF;
  END IF;
END;
/

DECLARE v_nullable VARCHAR2(1); v_exists NUMBER; BEGIN
  SELECT COUNT(*) INTO v_exists FROM USER_TAB_COLUMNS 
  WHERE TABLE_NAME = 'VAGA' AND COLUMN_NAME = 'NUMERO';
  IF v_exists > 0 THEN
    SELECT NULLABLE INTO v_nullable FROM USER_TAB_COLUMNS 
    WHERE TABLE_NAME = 'VAGA' AND COLUMN_NAME = 'NUMERO';
    IF v_nullable = 'Y' THEN
      EXECUTE IMMEDIATE 'ALTER TABLE VAGA MODIFY (NUMERO NOT NULL)';
    END IF;
  END IF;
END;
/

DECLARE v_nullable VARCHAR2(1); v_exists NUMBER; BEGIN
  SELECT COUNT(*) INTO v_exists FROM USER_TAB_COLUMNS 
  WHERE TABLE_NAME = 'MOTO' AND COLUMN_NAME = 'MODELO';
  IF v_exists > 0 THEN
    SELECT NULLABLE INTO v_nullable FROM USER_TAB_COLUMNS 
    WHERE TABLE_NAME = 'MOTO' AND COLUMN_NAME = 'MODELO';
    IF v_nullable = 'Y' THEN
      EXECUTE IMMEDIATE 'ALTER TABLE MOTO MODIFY (MODELO NOT NULL)';
    END IF;
  END IF;
END;
/

DECLARE v_nullable VARCHAR2(1); v_exists NUMBER; BEGIN
  SELECT COUNT(*) INTO v_exists FROM USER_TAB_COLUMNS 
  WHERE TABLE_NAME = 'MOTO' AND COLUMN_NAME = 'PROBLEMA_IDENTIFICADO';
  IF v_exists > 0 THEN
    SELECT NULLABLE INTO v_nullable FROM USER_TAB_COLUMNS 
    WHERE TABLE_NAME = 'MOTO' AND COLUMN_NAME = 'PROBLEMA_IDENTIFICADO';
    IF v_nullable = 'Y' THEN
      EXECUTE IMMEDIATE 'ALTER TABLE MOTO MODIFY (PROBLEMA_IDENTIFICADO NOT NULL)';
    END IF;
  END IF;
END;
/

DECLARE v_nullable VARCHAR2(1); v_exists NUMBER; BEGIN
  SELECT COUNT(*) INTO v_exists FROM USER_TAB_COLUMNS 
  WHERE TABLE_NAME = 'DEFEITO' AND COLUMN_NAME = 'DESCRICAO';
  IF v_exists > 0 THEN
    SELECT NULLABLE INTO v_nullable FROM USER_TAB_COLUMNS 
    WHERE TABLE_NAME = 'DEFEITO' AND COLUMN_NAME = 'DESCRICAO';
    IF v_nullable = 'Y' THEN
      EXECUTE IMMEDIATE 'ALTER TABLE DEFEITO MODIFY (DESCRICAO NOT NULL)';
    END IF;
  END IF;
END;
/

