-- V9: Add LOCALIZACAO column to PATIO (Oracle-safe and idempotent)

DECLARE v_table NUMBER; v_col NUMBER; BEGIN
  SELECT COUNT(*) INTO v_table FROM USER_TABLES WHERE TABLE_NAME = 'PATIO';
  IF v_table > 0 THEN
    SELECT COUNT(*) INTO v_col FROM USER_TAB_COLUMNS 
    WHERE TABLE_NAME = 'PATIO' AND COLUMN_NAME = 'LOCALIZACAO';
    IF v_col = 0 THEN
      EXECUTE IMMEDIATE 'ALTER TABLE PATIO ADD (LOCALIZACAO VARCHAR2(255))';
    END IF;
  END IF;
END;
/


